In [1]:
import seaborn as sns

In [2]:
tips = sns.load_dataset('tips')

In [3]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
6          8.77  2.00    Male     No   Sun  Dinner     2
7         26.88  3.12    Male     No   Sun  Dinner     4
8         15.04  1.96    Male     No   Sun  Dinner     2
9         14.78  3.23    Male     No   Sun  Dinner     2
10        10.27  1.71    Male     No   Sun  Dinner     2
11        35.26  5.00  Female     No   Sun  Dinner     4
12        15.42  1.57    Male     No   Sun  Dinner     2
13        18.43  3.00    Male     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
15        21.58  3.92    Male     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
17        16.29  3.71    Male     No   Sun  Dinner     3
18        16.97  3.50  Female     No   Sun  Dinner     3
19        20.65  3.35    Male     No   Sat  Dinner     3
20        17.92  4.08    Male     No   Sat  Dinner     2
21        20.29  2.75  Female     No   Sat  Dinner     2
22        15.77  2.23  Female     No   Sat  Dinner     2
23        39.42  7.58    Male     No   Sat  Dinner     4
24        19.82  3.18    Male     No   Sat  Dinner     2
25        17.81  2.34    Male     No   Sat  Dinner     4
26        13.37  2.00    Male     No   Sat  Dinner     2
27        12.69  2.00    Male     No   Sat  Dinner     2
28        21.70  4.30    Male     No   Sat  Dinner     2
29        19.65  3.00  Female     No   Sat  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
214       28.17  6.50  Female    Yes   Sat  Dinner     3
215       12.90  1.10  Female    Yes   Sat  Dinner     2
216       28.15  3.00    Male    Yes   Sat  Dinner     5
217       11.59  1.50    Male    Yes   Sat  Dinner     2
218        7.74  1.44    Male    Yes   Sat  Dinner     2
219       30.14  3.09  Female    Yes   Sat  Dinner     4
220       12.16  2.20    Male    Yes   Fri   Lunch     2
221       13.42  3.48  Female    Yes   Fri   Lunch     2
222        8.58  1.92    Male    Yes   Fri   Lunch     1
223       15.98  3.00  Female     No   Fri   Lunch     3
224       13.42  1.58    Male    Yes   Fri   Lunch     2
225       16.27  2.50  Female    Yes   Fri   Lunch     2
226       10.09  2.00  Female    Yes   Fri   Lunch     2
227       20.45  3.00    Male     No   Sat  Dinner     4
228       13.28  2.72    Male     No   Sat  Dinner     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
231       15.69  3.00    Male    Yes   Sat  Dinner     3
232       11.61  3.39    Male     No   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

## pandas map 3

apply, map, applymap

함수냐 dictionarly냐 serices

map은 시리즈에서만 쓸 수 있다.

apply는 시리즈 데이터 프레임에서 쓸 수 있다.

In [4]:
tips.sex.map??

In [5]:
tips.sex.map({'Male':1,'Female':2})

0      2
1      1
2      1
3      1
4      2
5      1
6      1
7      1
8      1
9      1
10     1
11     2
12     1
13     1
14     2
15     1
16     2
17     1
18     2
19     1
20     1
21     2
22     2
23     1
24     1
25     1
26     1
27     1
28     1
29     2
      ..
214    2
215    2
216    1
217    1
218    1
219    2
220    1
221    2
222    1
223    2
224    1
225    2
226    2
227    1
228    1
229    2
230    1
231    1
232    1
233    1
234    1
235    1
236    1
237    1
238    2
239    1
240    2
241    1
242    1
243    2
Name: sex, Length: 244, dtype: int64

In [6]:
tips.sex.map(lambda x:1 if x=='Male' else 2)

0      2
1      1
2      1
3      1
4      2
5      1
6      1
7      1
8      1
9      1
10     1
11     2
12     1
13     1
14     2
15     1
16     2
17     1
18     2
19     1
20     1
21     2
22     2
23     1
24     1
25     1
26     1
27     1
28     1
29     2
      ..
214    2
215    2
216    1
217    1
218    1
219    2
220    1
221    2
222    1
223    2
224    1
225    2
226    2
227    1
228    1
229    2
230    1
231    1
232    1
233    1
234    1
235    1
236    1
237    1
238    2
239    1
240    2
241    1
242    1
243    2
Name: sex, Length: 244, dtype: category
Categories (2, int64): [1, 2]

pandas는 데이터 렝글링 튤 : 간단한 기초분석 툴

numpy기반 함수형 패러다임 -> 엄청난 속도

In [16]:
tips.apply(lambda x : x['total_bill']+x['tip'] , axis=1 )

0      18.00
1      12.00
2      24.51
3      26.99
4      28.20
5      30.00
6      10.77
7      30.00
8      17.00
9      18.01
10     11.98
11     40.26
12     16.99
13     21.43
14     17.85
15     25.50
16     12.00
17     20.00
18     20.47
19     24.00
20     22.00
21     23.04
22     18.00
23     47.00
24     23.00
25     20.15
26     15.37
27     14.69
28     26.00
29     22.65
       ...
214    34.67
215    14.00
216    31.15
217    13.09
218     9.18
219    33.23
220    14.36
221    16.90
222    10.50
223    18.98
224    15.00
225    18.77
226    12.09
227    23.45
228    16.00
229    25.00
230    26.01
231    18.69
232    15.00
233    12.24
234    18.53
235    11.32
236    13.60
237    34.00
238    40.50
239    34.95
240    29.18
241    24.67
242    19.57
243    21.78
Length: 244, dtype: float64

In [11]:
tips[['total_bill','tip']].apply(lambda x:sum(x))

total_bill    4827.77
tip            731.58
dtype: float64

apply -> map과 약간 다르다 각각의 값을 구하고 싶을 때.

In [13]:
tips['ratio'] = tips.apply(lambda x:x['tip']/x['total_bill'], axis=1)

In [14]:
tips

     total_bill   tip     sex smoker   day    time  size     ratio
0         16.99  1.01  Female     No   Sun  Dinner     2  0.059447
1         10.34  1.66    Male     No   Sun  Dinner     3  0.160542
2         21.01  3.50    Male     No   Sun  Dinner     3  0.166587
3         23.68  3.31    Male     No   Sun  Dinner     2  0.139780
4         24.59  3.61  Female     No   Sun  Dinner     4  0.146808
5         25.29  4.71    Male     No   Sun  Dinner     4  0.186240
6          8.77  2.00    Male     No   Sun  Dinner     2  0.228050
7         26.88  3.12    Male     No   Sun  Dinner     4  0.116071
8         15.04  1.96    Male     No   Sun  Dinner     2  0.130319
9         14.78  3.23    Male     No   Sun  Dinner     2  0.218539
10        10.27  1.71    Male     No   Sun  Dinner     2  0.166504
11        35.26  5.00  Female     No   Sun  Dinner     4  0.141804
12        15.42  1.57    Male     No   Sun  Dinner     2  0.101816
13        18.43  3.00    Male     No   Sun  Dinner     4  0.162778
14        14.83  3.02  Female     No   Sun  Dinner     2  0.203641
15        21.58  3.92    Male     No   Sun  Dinner     2  0.181650
16        10.33  1.67  Female     No   Sun  Dinner     3  0.161665
17        16.29  3.71    Male     No   Sun  Dinner     3  0.227747
18        16.97  3.50  Female     No   Sun  Dinner     3  0.206246
19        20.65  3.35    Male     No   Sat  Dinner     3  0.162228
20        17.92  4.08    Male     No   Sat  Dinner     2  0.227679
21        20.29  2.75  Female     No   Sat  Dinner     2  0.135535
22        15.77  2.23  Female     No   Sat  Dinner     2  0.141408
23        39.42  7.58    Male     No   Sat  Dinner     4  0.192288
24        19.82  3.18    Male     No   Sat  Dinner     2  0.160444
25        17.81  2.34    Male     No   Sat  Dinner     4  0.131387
26        13.37  2.00    Male     No   Sat  Dinner     2  0.149589
27        12.69  2.00    Male     No   Sat  Dinner     2  0.157604
28        21.70  4.30    Male     No   Sat  Dinner     2  0.198157
29        19.65  3.00  Female     No   Sat  Dinner     2  0.152672
..          ...   ...     ...    ...   ...     ...   ...       ...
214       28.17  6.50  Female    Yes   Sat  Dinner     3  0.230742
215       12.90  1.10  Female    Yes   Sat  Dinner     2  0.085271
216       28.15  3.00    Male    Yes   Sat  Dinner     5  0.106572
217       11.59  1.50    Male    Yes   Sat  Dinner     2  0.129422
218        7.74  1.44    Male    Yes   Sat  Dinner     2  0.186047
219       30.14  3.09  Female    Yes   Sat  Dinner     4  0.102522
220       12.16  2.20    Male    Yes   Fri   Lunch     2  0.180921
221       13.42  3.48  Female    Yes   Fri   Lunch     2  0.259314
222        8.58  1.92    Male    Yes   Fri   Lunch     1  0.223776
223       15.98  3.00  Female     No   Fri   Lunch     3  0.187735
224       13.42  1.58    Male    Yes   Fri   Lunch     2  0.117735
225       16.27  2.50  Female    Yes   Fri   Lunch     2  0.153657
226       10.09  2.00  Female    Yes   Fri   Lunch     2  0.198216
227       20.45  3.00    Male     No   Sat  Dinner     4  0.146699
228       13.28  2.72    Male     No   Sat  Dinner     2  0.204819
229       22.12  2.88  Female    Yes   Sat  Dinner     2  0.130199
230       24.01  2.00    Male    Yes   Sat  Dinner     4  0.083299
231       15.69  3.00    Male    Yes   Sat  Dinner     3  0.191205
232       11.61  3.39    Male     No   Sat  Dinner     2  0.291990
233       10.77  1.47    Male     No   Sat  Dinner     2  0.136490
234       15.53  3.00    Male    Yes   Sat  Dinner     2  0.193175
235       10.07  1.25    Male     No   Sat  Dinner     2  0.124131
236       12.60  1.00    Male    Yes   Sat  Dinner     2  0.079365
237       32.83  1.17    Male    Yes   Sat  Dinner     2  0.035638
238       35.83  4.67  Female     No   Sat  Dinner     3  0.130338
239       29.03  5.92    Male     No   Sat  Dinner     3  0.203927
240       27.18  2.00  Female    Yes   Sat  Dinner     2  0.073584
241       22.67  2.00    Male    Yes   Sat  Dinner     2  0.088222
242       17.82  1.75    Male     No   Sat  Dinner     2  0.098204
243       18.78  3.00  Female     No  Thur  Dinner     2  0.159744

[244 rows x 8 columns]

컬럼이 많아지면 차원의 저주가 생긴다.

모델 학습이 잘 안되면 이상한 결과를 표현할 수 있다.

map3 랑 비슷한놈 ? transport

In [17]:
for i in tips.items():
    print(i)

('total_bill', 0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
5      25.29
6       8.77
7      26.88
8      15.04
9      14.78
10     10.27
11     35.26
12     15.42
13     18.43
14     14.83
15     21.58
16     10.33
17     16.29
18     16.97
19     20.65
20     17.92
21     20.29
22     15.77
23     39.42
24     19.82
25     17.81
26     13.37
27     12.69
28     21.70
29     19.65
       ...
214    28.17
215    12.90
216    28.15
217    11.59
218     7.74
219    30.14
220    12.16
221    13.42
222     8.58
223    15.98
224    13.42
225    16.27
226    10.09
227    20.45
228    13.28
229    22.12
230    24.01
231    15.69
232    11.61
233    10.77
234    15.53
235    10.07
236    12.60
237    32.83
238    35.83
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64)
('tip', 0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
5      4.71
6      2.00
7      3.12
8      1.96
9      3.23
10     1.71
11     5.00
12     1.57
13     3.00
14     3.02
15     3.92
16     1.67
17     3.71
18     3.50
19     3.35
20     4.08
21     2.75
22     2.23
23     7.58
24     3.18
25     2.34
26     2.00
27     2.00
28     4.30
29     3.00
       ...
214    6.50
215    1.10
216    3.00
217    1.50
218    1.44
219    3.09
220    2.20
221    3.48
222    1.92
223    3.00
224    1.58
225    2.50
226    2.00
227    3.00
228    2.72
229    2.88
230    2.00
231    3.00
232    3.39
233    1.47
234    3.00
235    1.25
236    1.00
237    1.17
238    4.67
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64)
('sex', 0      Female
1        Male
2        Male
3        Male
4      Female
5        Male
6        Male
7        Male
8        Male
9        Male
10       Male
11     Female
12       Male
13       Male
14     Female
15       Male
16     Female
17       Male
18     Female
19       Male
20       Male
21     Female
22     Female
23       Male
24       Male
25       Male
26       Male
27       Male
28       Male
29     Female
        ...
214    Female
215    Female
216      Male
217      Male
218      Male
219    Female
220      Male
221    Female
222      Male
223    Female
224      Male
225    Female
226    Female
227      Male
228      Male
229    Female
230      Male
231      Male
232      Male
233      Male
234      Male
235      Male
236      Male
237      Male
238    Female
239      Male
240    Female
241      Male
242      Male
243    Female
Name: sex, Length: 244, dtype: category
Categories (2, object): [Male, Female])
('smoker', 0       No
1       No
2       No
3       No
4       No
5       No
6       No
7       No
8       No
9       No
10      No
11      No
12      No
13      No
14      No
15      No
16      No
17      No
18      No
19      No
20      No
21      No
22      No
23      No
24      No
25      No
26      No
27      No
28      No
29      No
      ...
214    Yes
215    Yes
216    Yes
217    Yes
218    Yes
219    Yes
220    Yes
221    Yes
222    Yes
223     No
224    Yes
225    Yes
226    Yes
227     No
228     No
229    Yes
230    Yes
231    Yes
232     No
233     No
234    Yes
235     No
236    Yes
237    Yes
238     No
239     No
240    Yes
241    Yes
242     No
243     No
Name: smoker, Length: 244, dtype: category
Categories (2, object): [Yes, No])
('day', 0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
5       Sun
6       Sun
7       Sun
8       Sun
9       Sun
10      Sun
11      Sun
12      Sun
13      Sun
14      Sun
15      Sun
16      Sun
17      Sun
18      Sun
19      Sat
20      Sat
21      Sat
22      Sat
23      Sat
24      Sat
25      Sat
26      Sat
27      Sat
28      Sat
29      Sat
       ...
214     Sat
215     Sat
216     Sat
217     Sat
218     Sat
219     Sat
220     Fri
221     Fri
222     Fri
223     Fri
224     Fri
225     Fri
226     Fri
227     Sat
228     Sat
229     Sat
230     Sat
231     Sat
232     Sat
233     Sat
234     Sat
235     Sat
236     Sat
237     Sat
238     Sat
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, object): [Thur, Fri, Sat, Sun])
('time', 0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
5      Dinner
6      Dinner
7      Dinner
8      Dinner
9      Dinner
10     Dinner
11     Dinner
12     Dinner
13     Dinner
14     Dinner
15     Dinner
16     Dinner
17     Dinner
18     Dinner
19     Dinner
20     Dinner
21     Dinner
22     Dinner
23     Dinner
24     Dinner
25     Dinner
26     Dinner
27     Dinner
28     Dinner
29     Dinner
        ...
214    Dinner
215    Dinner
216    Dinner
217    Dinner
218    Dinner
219    Dinner
220     Lunch
221     Lunch
222     Lunch
223     Lunch
224     Lunch
225     Lunch
226     Lunch
227    Dinner
228    Dinner
229    Dinner
230    Dinner
231    Dinner
232    Dinner
233    Dinner
234    Dinner
235    Dinner
236    Dinner
237    Dinner
238    Dinner
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: category
Categories (2, object): [Lunch, Dinner])
('size', 0      2
1      3
2      3
3      2
4      4
5      4
6      2
7      4
8      2
9      2
10     2
11     4
12     2
13     4
14     2
15     2
16     3
17     3
18     3
19     3
20     2
21     2
22     2
23     4
24     2
25     4
26     2
27     2
28     2
29     2
      ..
214    3
215    2
216    5
217    2
218    2
219    4
220    2
221    2
222    1
223    3
224    2
225    2
226    2
227    4
228    2
229    2
230    4
231    3
232    2
233    2
234    2
235    2
236    2
237    2
238    3
239    3
240    2
241    2
242    2
243    2
Name: size, Length: 244, dtype: int64)
('ratio', 0      0.059447
1      0.160542
2      0.166587
3      0.139780
4      0.146808
5      0.186240
6      0.228050
7      0.116071
8      0.130319
9      0.218539
10     0.166504
11     0.141804
12     0.101816
13     0.162778
14     0.203641
15     0.181650
16     0.161665
17     0.227747
18     0.206246
19     0.162228
20     0.227679
21     0.135535
22     0.141408
23     0.192288
24     0.160444
25     0.131387
26     0.149589
27     0.157604
28     0.198157
29     0.152672
         ...
214    0.230742
215    0.085271
216    0.106572
217    0.129422
218    0.186047
219    0.102522
220    0.180921
221    0.259314
222    0.223776
223    0.187735
224    0.117735
225    0.153657
226    0.198216
227    0.146699
228    0.204819
229    0.130199
230    0.083299
231    0.191205
232    0.291990
233    0.136490
234    0.193175
235    0.124131
236    0.079365
237    0.035638
238    0.130338
239    0.203927
240    0.073584
241    0.088222
242    0.098204
243    0.159744
Name: ratio, Length: 244, dtype: float64)

In [18]:
for i in tips.iteritems():
    print(i)

('total_bill', 0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
5      25.29
6       8.77
7      26.88
8      15.04
9      14.78
10     10.27
11     35.26
12     15.42
13     18.43
14     14.83
15     21.58
16     10.33
17     16.29
18     16.97
19     20.65
20     17.92
21     20.29
22     15.77
23     39.42
24     19.82
25     17.81
26     13.37
27     12.69
28     21.70
29     19.65
       ...
214    28.17
215    12.90
216    28.15
217    11.59
218     7.74
219    30.14
220    12.16
221    13.42
222     8.58
223    15.98
224    13.42
225    16.27
226    10.09
227    20.45
228    13.28
229    22.12
230    24.01
231    15.69
232    11.61
233    10.77
234    15.53
235    10.07
236    12.60
237    32.83
238    35.83
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64)
('tip', 0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
5      4.71
6      2.00
7      3.12
8      1.96
9      3.23
10     1.71
11     5.00
12     1.57
13     3.00
14     3.02
15     3.92
16     1.67
17     3.71
18     3.50
19     3.35
20     4.08
21     2.75
22     2.23
23     7.58
24     3.18
25     2.34
26     2.00
27     2.00
28     4.30
29     3.00
       ...
214    6.50
215    1.10
216    3.00
217    1.50
218    1.44
219    3.09
220    2.20
221    3.48
222    1.92
223    3.00
224    1.58
225    2.50
226    2.00
227    3.00
228    2.72
229    2.88
230    2.00
231    3.00
232    3.39
233    1.47
234    3.00
235    1.25
236    1.00
237    1.17
238    4.67
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64)
('sex', 0      Female
1        Male
2        Male
3        Male
4      Female
5        Male
6        Male
7        Male
8        Male
9        Male
10       Male
11     Female
12       Male
13       Male
14     Female
15       Male
16     Female
17       Male
18     Female
19       Male
20       Male
21     Female
22     Female
23       Male
24       Male
25       Male
26       Male
27       Male
28       Male
29     Female
        ...
214    Female
215    Female
216      Male
217      Male
218      Male
219    Female
220      Male
221    Female
222      Male
223    Female
224      Male
225    Female
226    Female
227      Male
228      Male
229    Female
230      Male
231      Male
232      Male
233      Male
234      Male
235      Male
236      Male
237      Male
238    Female
239      Male
240    Female
241      Male
242      Male
243    Female
Name: sex, Length: 244, dtype: category
Categories (2, object): [Male, Female])
('smoker', 0       No
1       No
2       No
3       No
4       No
5       No
6       No
7       No
8       No
9       No
10      No
11      No
12      No
13      No
14      No
15      No
16      No
17      No
18      No
19      No
20      No
21      No
22      No
23      No
24      No
25      No
26      No
27      No
28      No
29      No
      ...
214    Yes
215    Yes
216    Yes
217    Yes
218    Yes
219    Yes
220    Yes
221    Yes
222    Yes
223     No
224    Yes
225    Yes
226    Yes
227     No
228     No
229    Yes
230    Yes
231    Yes
232     No
233     No
234    Yes
235     No
236    Yes
237    Yes
238     No
239     No
240    Yes
241    Yes
242     No
243     No
Name: smoker, Length: 244, dtype: category
Categories (2, object): [Yes, No])
('day', 0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
5       Sun
6       Sun
7       Sun
8       Sun
9       Sun
10      Sun
11      Sun
12      Sun
13      Sun
14      Sun
15      Sun
16      Sun
17      Sun
18      Sun
19      Sat
20      Sat
21      Sat
22      Sat
23      Sat
24      Sat
25      Sat
26      Sat
27      Sat
28      Sat
29      Sat
       ...
214     Sat
215     Sat
216     Sat
217     Sat
218     Sat
219     Sat
220     Fri
221     Fri
222     Fri
223     Fri
224     Fri
225     Fri
226     Fri
227     Sat
228     Sat
229     Sat
230     Sat
231     Sat
232     Sat
233     Sat
234     Sat
235     Sat
236     Sat
237     Sat
238     Sat
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, object): [Thur, Fri, Sat, Sun])
('time', 0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
5      Dinner
6      Dinner
7      Dinner
8      Dinner
9      Dinner
10     Dinner
11     Dinner
12     Dinner
13     Dinner
14     Dinner
15     Dinner
16     Dinner
17     Dinner
18     Dinner
19     Dinner
20     Dinner
21     Dinner
22     Dinner
23     Dinner
24     Dinner
25     Dinner
26     Dinner
27     Dinner
28     Dinner
29     Dinner
        ...
214    Dinner
215    Dinner
216    Dinner
217    Dinner
218    Dinner
219    Dinner
220     Lunch
221     Lunch
222     Lunch
223     Lunch
224     Lunch
225     Lunch
226     Lunch
227    Dinner
228    Dinner
229    Dinner
230    Dinner
231    Dinner
232    Dinner
233    Dinner
234    Dinner
235    Dinner
236    Dinner
237    Dinner
238    Dinner
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: category
Categories (2, object): [Lunch, Dinner])
('size', 0      2
1      3
2      3
3      2
4      4
5      4
6      2
7      4
8      2
9      2
10     2
11     4
12     2
13     4
14     2
15     2
16     3
17     3
18     3
19     3
20     2
21     2
22     2
23     4
24     2
25     4
26     2
27     2
28     2
29     2
      ..
214    3
215    2
216    5
217    2
218    2
219    4
220    2
221    2
222    1
223    3
224    2
225    2
226    2
227    4
228    2
229    2
230    4
231    3
232    2
233    2
234    2
235    2
236    2
237    2
238    3
239    3
240    2
241    2
242    2
243    2
Name: size, Length: 244, dtype: int64)
('ratio', 0      0.059447
1      0.160542
2      0.166587
3      0.139780
4      0.146808
5      0.186240
6      0.228050
7      0.116071
8      0.130319
9      0.218539
10     0.166504
11     0.141804
12     0.101816
13     0.162778
14     0.203641
15     0.181650
16     0.161665
17     0.227747
18     0.206246
19     0.162228
20     0.227679
21     0.135535
22     0.141408
23     0.192288
24     0.160444
25     0.131387
26     0.149589
27     0.157604
28     0.198157
29     0.152672
         ...
214    0.230742
215    0.085271
216    0.106572
217    0.129422
218    0.186047
219    0.102522
220    0.180921
221    0.259314
222    0.223776
223    0.187735
224    0.117735
225    0.153657
226    0.198216
227    0.146699
228    0.204819
229    0.130199
230    0.083299
231    0.191205
232    0.291990
233    0.136490
234    0.193175
235    0.124131
236    0.079365
237    0.035638
238    0.130338
239    0.203927
240    0.073584
241    0.088222
242    0.098204
243    0.159744
Name: ratio, Length: 244, dtype: float64)

In [19]:
for i in tips.iterrows():
    print(i)

(0, total_bill        16.99
tip                1.01
sex              Female
smoker               No
day                 Sun
time             Dinner
size                  2
ratio         0.0594467
Name: 0, dtype: object)
(1, total_bill       10.34
tip               1.66
sex               Male
smoker              No
day                Sun
time            Dinner
size                 3
ratio         0.160542
Name: 1, dtype: object)
(2, total_bill       21.01
tip                3.5
sex               Male
smoker              No
day                Sun
time            Dinner
size                 3
ratio         0.166587
Name: 2, dtype: object)
(3, total_bill      23.68
tip              3.31
sex              Male
smoker             No
day               Sun
time           Dinner
size                2
ratio         0.13978
Name: 3, dtype: object)
(4, total_bill       24.59
tip               3.61
sex             Female
smoker              No
day                Sun
time            Dinner
size                 4
ratio         0.146808
Name: 4, dtype: object)
(5, total_bill      25.29
tip              4.71
sex              Male
smoker             No
day               Sun
time           Dinner
size                4
ratio         0.18624
Name: 5, dtype: object)
(6, total_bill       8.77
tip                 2
sex              Male
smoker             No
day               Sun
time           Dinner
size                2
ratio         0.22805
Name: 6, dtype: object)
(7, total_bill       26.88
tip               3.12
sex               Male
smoker              No
day                Sun
time            Dinner
size                 4
ratio         0.116071
Name: 7, dtype: object)
(8, total_bill       15.04
tip               1.96
sex               Male
smoker              No
day                Sun
time            Dinner
size                 2
ratio         0.130319
Name: 8, dtype: object)
(9, total_bill       14.78
tip               3.23
sex               Male
smoker              No
day                Sun
time            Dinner
size                 2
ratio         0.218539
Name: 9, dtype: object)
(10, total_bill       10.27
tip               1.71
sex               Male
smoker              No
day                Sun
time            Dinner
size                 2
ratio         0.166504
Name: 10, dtype: object)
(11, total_bill       35.26
tip                  5
sex             Female
smoker              No
day                Sun
time            Dinner
size                 4
ratio         0.141804
Name: 11, dtype: object)
(12, total_bill       15.42
tip               1.57
sex               Male
smoker              No
day                Sun
time            Dinner
size                 2
ratio         0.101816
Name: 12, dtype: object)
(13, total_bill       18.43
tip                  3
sex               Male
smoker              No
day                Sun
time            Dinner
size                 4
ratio         0.162778
Name: 13, dtype: object)
(14, total_bill       14.83
tip               3.02
sex             Female
smoker              No
day                Sun
time            Dinner
size                 2
ratio         0.203641
Name: 14, dtype: object)
(15, total_bill      21.58
tip              3.92
sex              Male
smoker             No
day               Sun
time           Dinner
size                2
ratio         0.18165
Name: 15, dtype: object)
(16, total_bill       10.33
tip               1.67
sex             Female
smoker              No
day                Sun
time            Dinner
size                 3
ratio         0.161665
Name: 16, dtype: object)
(17, total_bill       16.29
tip               3.71
sex               Male
smoker              No
day                Sun
time            Dinner
size                 3
ratio         0.227747
Name: 17, dtype: object)
(18, total_bill       16.97
tip                3.5
sex             Female
smoker              No
day                Sun
time            Dinner
size                 3
ratio         0.206246
Name: 18, dtype: object)
(19, total_bill       20.65
tip               3.35
sex               Male
smoker              No
day                Sat
time            Dinner
size                 3
ratio         0.162228
Name: 19, dtype: object)
(20, total_bill       17.92
tip               4.08
sex               Male
smoker              No
day                Sat
time            Dinner
size                 2
ratio         0.227679
Name: 20, dtype: object)
(21, total_bill       20.29
tip               2.75
sex             Female
smoker              No
day                Sat
time            Dinner
size                 2
ratio         0.135535
Name: 21, dtype: object)
(22, total_bill       15.77
tip               2.23
sex             Female
smoker              No
day                Sat
time            Dinner
size                 2
ratio         0.141408
Name: 22, dtype: object)
(23, total_bill       39.42
tip               7.58
sex               Male
smoker              No
day                Sat
time            Dinner
size                 4
ratio         0.192288
Name: 23, dtype: object)
(24, total_bill       19.82
tip               3.18
sex               Male
smoker              No
day                Sat
time            Dinner
size                 2
ratio         0.160444
Name: 24, dtype: object)
(25, total_bill       17.81
tip               2.34
sex               Male
smoker              No
day                Sat
time            Dinner
size                 4
ratio         0.131387
Name: 25, dtype: object)
(26, total_bill       13.37
tip                  2
sex               Male
smoker              No
day                Sat
time            Dinner
size                 2
ratio         0.149589
Name: 26, dtype: object)
(27, total_bill       12.69
tip                  2
sex               Male
smoker              No
day                Sat
time            Dinner
size                 2
ratio         0.157604
Name: 27, dtype: object)
(28, total_bill        21.7
tip                4.3
sex               Male
smoker              No
day                Sat
time            Dinner
size                 2
ratio         0.198157
Name: 28, dtype: object)
(29, total_bill       19.65
tip                  3
sex             Female
smoker              No
day                Sat
time            Dinner
size                 2
ratio         0.152672
Name: 29, dtype: object)
(30, total_bill        9.55
tip               1.45
sex               Male
smoker              No
day                Sat
time            Dinner
size                 2
ratio         0.151832
Name: 30, dtype: object)
(31, total_bill      18.35
tip               2.5
sex              Male
smoker             No
day               Sat
time           Dinner
size                4
ratio         0.13624
Name: 31, dtype: object)
(32, total_bill       15.06
tip                  3
sex             Female
smoker              No
day                Sat
time            Dinner
size                 2
ratio         0.199203
Name: 32, dtype: object)
(33, total_bill       20.69
tip               2.45
sex             Female
smoker              No
day                Sat
time            Dinner
size                 4
ratio         0.118415
Name: 33, dtype: object)
(34, total_bill       17.78
tip               3.27
sex               Male
smoker              No
day                Sat
time            Dinner
size                 2
ratio         0.183915
Name: 34, dtype: object)
(35, total_bill       24.06
tip                3.6
sex               Male
smoker              No
day                Sat
time            Dinner
size                 3
ratio         0.149626
Name: 35, dtype: object)
(36, total_bill       16.31
tip                  2
sex               Male
smoker              No
day                Sat
time            Dinner
size                 3
ratio         0.122624
Name: 36, dtype: object)
(37, total_bill       16.93
tip               3.07
sex             Female
smoker              No
day                Sat
time            Dinner
size                 3
ratio         0.181335
Name: 37, dtype: object)
(38, total_bill       18.69
tip               2.31
sex               Male
smoker              No
day                Sat
time            Dinner
size                 3
ratio         0.123596
Name: 38, dtype: object)
(39, total_bill       31.27
tip                  5
sex               Male
smoker              No
day                Sat
time            Dinner
size                 3
ratio         0.159898
Name: 39, dtype: object)
(40, total_bill       16.04
tip               2.24
sex               Male
smoker              No
day                Sat
time            Dinner
size                 3
ratio         0.139651
Name: 40, dtype: object)
(41, total_bill       17.46
tip               2.54
sex               Male
smoker              No
day                Sun
time            Dinner
size                 2
ratio         0.145475
Name: 41, dtype: object)
(42, total_bill       13.94
tip               3.06
sex               Male
smoker              No
day                Sun
time            Dinner
size                 2
ratio         0.219512
Name: 42, dtype: object)
(43, total_bill        9.68
tip               1.32
sex               Male
smoker              No
day                Sun
time            Dinner
size                 2
ratio         0.136364
Name: 43, dtype: object)
(44, total_bill        30.4
tip                5.6
sex               Male
smoker              No
day                Sun
time            Dinner
size                 4
ratio         0.184211
Name: 44, dtype: object)
(45, total_bill       18.29
tip                  3
sex               Male
smoker              No
day                Sun
time            Dinner
size                 2
ratio         0.164024
Name: 45, dtype: object)
(46, total_bill       22.23
tip                  5
sex               Male
smoker              No
day                Sun
time            Dinner
size                 2
ratio         0.224921
Name: 46, dtype: object)
(47, total_bill        32.4
tip                  6
sex               Male
smoker              No
day                Sun
time            Dinner
size                 4
ratio         0.185185
Name: 47, dtype: object)
(48, total_bill        28.55
tip                2.05
sex                Male
smoker               No
day                 Sun
time             Dinner
size                  3
ratio         0.0718039
Name: 48, dtype: object)
(49, total_bill       18.04
tip                  3
sex               Male
smoker              No
day                Sun
time            Dinner
size                 2
ratio         0.166297
Name: 49, dtype: object)
(50, total_bill       12.54
tip                2.5
sex               Male
smoker              No
day                Sun
time            Dinner
size                 2
ratio         0.199362
Name: 50, dtype: object)
(51, total_bill       10.29
tip                2.6
sex             Female
smoker              No
day                Sun
time            Dinner
size                 2
ratio         0.252672
Name: 51, dtype: object)
(52, total_bill       34.81
tip                5.2
sex             Female
smoker              No
day                Sun
time            Dinner
size                 4
ratio         0.149382
Name: 52, dtype: object)
(53, total_bill        9.94
tip               1.56
sex               Male
smoker              No
day                Sun
time            Dinner
size                 2
ratio         0.156942
Name: 53, dtype: object)
(54, total_bill       25.56
tip               4.34
sex               Male
smoker              No
day                Sun
time            Dinner
size                 4
ratio         0.169797
Name: 54, dtype: object)
(55, total_bill       19.49
tip               3.51
sex               Male
smoker              No
day                Sun
time            Dinner
size                 2
ratio         0.180092
Name: 55, dtype: object)
(56, total_bill        38.01
tip                   3
sex                Male
smoker              Yes
day                 Sat
time             Dinner
size                  4
ratio         0.0789266
Name: 56, dtype: object)
(57, total_bill        26.41
tip                 1.5
sex              Female
smoker               No
day                 Sat
time             Dinner
size                  2
ratio         0.0567967
Name: 57, dtype: object)
(58, total_bill       11.24
tip               1.76
sex               Male
smoker             Yes
day                Sat
time            Dinner
size                 2
ratio         0.156584
Name: 58, dtype: object)
(59, total_bill       48.27
tip               6.73
sex               Male
smoker              No
day                Sat
time            Dinner
size                 4
ratio         0.139424
Name: 59, dtype: object)
(60, total_bill       20.29
tip               3.21
sex               Male
smoker             Yes
day                Sat
time            Dinner
size                 2
ratio         0.158206
Name: 60, dtype: object)
(61, total_bill       13.81
tip                  2
sex               Male
smoker             Yes
day                Sat
time            Dinner
size                 2
ratio         0.144823
Name: 61, dtype: object)
(62, total_bill       11.02
tip               1.98
sex               Male
smoker             Yes
day                Sat
time            Dinner
size                 2
ratio         0.179673
Name: 62, dtype: object)
(63, total_bill       18.29
tip               3.76
sex               Male
smoker             Yes
day                Sat
time            Dinner
size                 4
ratio         0.205577
Name: 63, dtype: object)
(64, total_bill       17.59
tip               2.64
sex               Male
smoker              No
day                Sat
time            Dinner
size                 3
ratio         0.150085
Name: 64, dtype: object)
(65, total_bill       20.08
tip               3.15
sex               Male
smoker              No
day                Sat
time            Dinner
size                 3
ratio         0.156873
Name: 65, dtype: object)
(66, total_bill       16.45
tip               2.47
sex             Female
smoker              No
day                Sat
time            Dinner
size                 2
ratio         0.150152
Name: 66, dtype: object)
(67, total_bill        3.07
tip                  1
sex             Female
smoker             Yes
day                Sat
time            Dinner
size                 1
ratio         0.325733
Name: 67, dtype: object)
(68, total_bill        20.23
tip                2.01
sex                Male
smoker               No
day                 Sat
time             Dinner
size                  2
ratio         0.0993574
Name: 68, dtype: object)
(69, total_bill       15.01
tip               2.09
sex               Male
smoker             Yes
day                Sat
time            Dinner
size                 2
ratio         0.139241
Name: 69, dtype: object)
(70, total_bill       12.02
tip               1.97
sex               Male
smoker              No
day                Sat
time            Dinner
size                 2
ratio         0.163894
Name: 70, dtype: object)
(71, total_bill       17.07
tip                  3
sex             Female
smoker              No
day                Sat
time            Dinner
size                 3
ratio         0.175747
Name: 71, dtype: object)
(72, total_bill       26.86
tip               3.14
sex             Female
smoker             Yes
day                Sat
time            Dinner
size                 2
ratio         0.116902
Name: 72, dtype: object)
(73, total_bill       25.28
tip                  5
sex             Female
smoker             Yes
day                Sat
time            Dinner
size                 2
ratio         0.197785
Name: 73, dtype: object)
(74, total_bill       14.73
tip                2.2
sex             Female
smoker              No
day                Sat
time            Dinner
size                 2
ratio         0.149355
Name: 74, dtype: object)
(75, total_bill       10.51
tip               1.25
sex               Male
smoker              No
day                Sat
time            Dinner
size                 2
ratio         0.118934
Name: 75, dtype: object)
(76, total_bill       17.92
tip               3.08
sex               Male
smoker             Yes
day                Sat
time            Dinner
size                 2
ratio         0.171875
Name: 76, dtype: object)
(77, total_bill        27.2
tip                  4
sex               Male
smoker              No
day               Thur
time             Lunch
size                 4
ratio         0.147059
Name: 77, dtype: object)
(78, total_bill      22.76
tip                 3
sex              Male
smoker             No
day              Thur
time            Lunch
size                2
ratio         0.13181
Name: 78, dtype: object)
(79, total_bill       17.29
tip               2.71
sex               Male
smoker              No
day               Thur
time             Lunch
size                 2
ratio         0.156738
Name: 79, dtype: object)
(80, total_bill       19.44
tip                  3
sex               Male
smoker             Yes
day               Thur
time             Lunch
size                 2
ratio         0.154321
Name: 80, dtype: object)
(81, total_bill       16.66
tip                3.4
sex               Male
smoker              No
day               Thur
time             Lunch
size                 2
ratio         0.204082
Name: 81, dtype: object)
(82, total_bill       10.07
tip               1.83
sex             Female
smoker              No
day               Thur
time             Lunch
size                 1
ratio         0.181728
Name: 82, dtype: object)
(83, total_bill       32.68
tip                  5
sex               Male
smoker             Yes
day               Thur
time             Lunch
size                 2
ratio         0.152999
Name: 83, dtype: object)
(84, total_bill       15.98
tip               2.03
sex               Male
smoker              No
day               Thur
time             Lunch
size                 2
ratio         0.127034
Name: 84, dtype: object)
(85, total_bill       34.83
tip               5.17
sex             Female
smoker              No
day               Thur
time             Lunch
size                 4
ratio         0.148435
Name: 85, dtype: object)
(86, total_bill       13.03
tip                  2
sex               Male
smoker              No
day               Thur
time             Lunch
size                 2
ratio         0.153492
Name: 86, dtype: object)
(87, total_bill       18.28
tip                  4
sex               Male
smoker              No
day               Thur
time             Lunch
size                 2
ratio         0.218818
Name: 87, dtype: object)
(88, total_bill       24.71
tip               5.85
sex               Male
smoker              No
day               Thur
time             Lunch
size                 2
ratio         0.236746
Name: 88, dtype: object)
(89, total_bill       21.16
tip                  3
sex               Male
smoker              No
day               Thur
time             Lunch
size                 2
ratio         0.141777
Name: 89, dtype: object)
(90, total_bill       28.97
tip                  3
sex               Male
smoker             Yes
day                Fri
time            Dinner
size                 2
ratio         0.103555
Name: 90, dtype: object)
(91, total_bill       22.49
tip                3.5
sex               Male
smoker              No
day                Fri
time            Dinner
size                 2
ratio         0.155625
Name: 91, dtype: object)
(92, total_bill        5.75
tip                  1
sex             Female
smoker             Yes
day                Fri
time            Dinner
size                 2
ratio         0.173913
Name: 92, dtype: object)
(93, total_bill      16.32
tip               4.3
sex            Female
smoker            Yes
day               Fri

Name: 203, dtype: object)
(204, total_bill       20.53
tip                  4
sex               Male
smoker             Yes
day               Thur
time             Lunch
size                 4
ratio         0.194837
Name: 204, dtype: object)
(205, total_bill       16.47
tip               3.23
sex             Female
smoker             Yes
day               Thur
time             Lunch
size                 3
ratio         0.196114
Name: 205, dtype: object)
(206, total_bill       26.59
tip               3.41
sex               Male
smoker             Yes
day                Sat
time            Dinner
size                 3
ratio         0.128244
Name: 206, dtype: object)
(207, total_bill        38.73
tip                   3
sex                Male
smoker              Yes
day                 Sat
time             Dinner
size                  4
ratio         0.0774593
Name: 207, dtype: object)
(208, total_bill        24.27
tip                2.03
sex                Male
smoker              Yes
day                 Sat
time             Dinner
size                  2
ratio         0.0836424
Name: 208, dtype: object)
(209, total_bill       12.76
tip               2.23
sex             Female
smoker             Yes
day                Sat
time            Dinner
size                 2
ratio         0.174765
Name: 209, dtype: object)
(210, total_bill        30.06
tip                   2
sex                Male
smoker              Yes
day                 Sat
time             Dinner
size                  3
ratio         0.0665336
Name: 210, dtype: object)
(211, total_bill       25.89
tip               5.16
sex               Male
smoker             Yes
day                Sat
time            Dinner
size                 4
ratio         0.199305
Name: 211, dtype: object)
(212, total_bill      48.33
tip                 9
sex              Male
smoker             No
day               Sat
time           Dinner
size                4
ratio         0.18622
Name: 212, dtype: object)
(213, total_bill       13.27
tip                2.5
sex             Female
smoker             Yes
day                Sat
time            Dinner
size                 2
ratio         0.188395
Name: 213, dtype: object)
(214, total_bill       28.17
tip                6.5
sex             Female
smoker             Yes
day                Sat
time            Dinner
size                 3
ratio         0.230742
Name: 214, dtype: object)
(215, total_bill         12.9
tip                 1.1
sex              Female
smoker              Yes
day                 Sat
time             Dinner
size                  2
ratio         0.0852713
Name: 215, dtype: object)
(216, total_bill       28.15
tip                  3
sex               Male
smoker             Yes
day                Sat
time            Dinner
size                 5
ratio         0.106572
Name: 216, dtype: object)
(217, total_bill       11.59
tip                1.5
sex               Male
smoker             Yes
day                Sat
time            Dinner
size                 2
ratio         0.129422
Name: 217, dtype: object)
(218, total_bill        7.74
tip               1.44
sex               Male
smoker             Yes
day                Sat
time            Dinner
size                 2
ratio         0.186047
Name: 218, dtype: object)
(219, total_bill       30.14
tip               3.09
sex             Female
smoker             Yes
day                Sat
time            Dinner
size                 4
ratio         0.102522
Name: 219, dtype: object)
(220, total_bill       12.16
tip                2.2
sex               Male
smoker             Yes
day                Fri
time             Lunch
size                 2
ratio         0.180921
Name: 220, dtype: object)
(221, total_bill       13.42
tip               3.48
sex             Female
smoker             Yes
day                Fri
time             Lunch
size                 2
ratio         0.259314
Name: 221, dtype: object)
(222, total_bill        8.58
tip               1.92
sex               Male
smoker             Yes
day                Fri
time             Lunch
size                 1
ratio         0.223776
Name: 222, dtype: object)
(223, total_bill       15.98
tip                  3
sex             Female
smoker              No
day                Fri
time             Lunch
size                 3
ratio         0.187735
Name: 223, dtype: object)
(224, total_bill       13.42
tip               1.58
sex               Male
smoker             Yes
day                Fri
time             Lunch
size                 2
ratio         0.117735
Name: 224, dtype: object)
(225, total_bill       16.27
tip                2.5
sex             Female
smoker             Yes
day                Fri
time             Lunch
size                 2
ratio         0.153657
Name: 225, dtype: object)
(226, total_bill       10.09
tip                  2
sex             Female
smoker             Yes
day                Fri
time             Lunch
size                 2
ratio         0.198216
Name: 226, dtype: object)
(227, total_bill       20.45
tip                  3
sex               Male
smoker              No
day                Sat
time            Dinner
size                 4
ratio         0.146699
Name: 227, dtype: object)
(228, total_bill       13.28
tip               2.72
sex               Male
smoker              No
day                Sat
time            Dinner
size                 2
ratio         0.204819
Name: 228, dtype: object)
(229, total_bill       22.12
tip               2.88
sex             Female
smoker             Yes
day                Sat
time            Dinner
size                 2
ratio         0.130199
Name: 229, dtype: object)
(230, total_bill        24.01
tip                   2
sex                Male
smoker              Yes
day                 Sat
time             Dinner
size                  4
ratio         0.0832986
Name: 230, dtype: object)
(231, total_bill       15.69
tip                  3
sex               Male
smoker             Yes
day                Sat
time            Dinner
size                 3
ratio         0.191205
Name: 231, dtype: object)
(232, total_bill      11.61
tip              3.39
sex              Male
smoker             No
day               Sat
time           Dinner
size                2
ratio         0.29199
Name: 232, dtype: object)
(233, total_bill      10.77
tip              1.47
sex              Male
smoker             No
day               Sat
time           Dinner
size                2
ratio         0.13649
Name: 233, dtype: object)
(234, total_bill       15.53
tip                  3
sex               Male
smoker             Yes
day                Sat
time            Dinner
size                 2
ratio         0.193175
Name: 234, dtype: object)
(235, total_bill       10.07
tip               1.25
sex               Male
smoker              No
day                Sat
time            Dinner
size                 2
ratio         0.124131
Name: 235, dtype: object)
(236, total_bill         12.6
tip                   1
sex                Male
smoker              Yes
day                 Sat
time             Dinner
size                  2
ratio         0.0793651
Name: 236, dtype: object)
(237, total_bill        32.83
tip                1.17
sex                Male
smoker              Yes
day                 Sat
time             Dinner
size                  2
ratio         0.0356381
Name: 237, dtype: object)
(238, total_bill       35.83
tip               4.67
sex             Female
smoker              No
day                Sat
time            Dinner
size                 3
ratio         0.130338
Name: 238, dtype: object)
(239, total_bill       29.03
tip               5.92
sex               Male
smoker              No
day                Sat
time            Dinner
size                 3
ratio         0.203927
Name: 239, dtype: object)
(240, total_bill        27.18
tip                   2
sex              Female
smoker              Yes
day                 Sat
time             Dinner
size                  2
ratio         0.0735835
Name: 240, dtype: object)
(241, total_bill        22.67
tip                   2
sex                Male
smoker              Yes
day                 Sat
time             Dinner
size                  2
ratio         0.0882223
Name: 241, dtype: object)
(242, total_bill        17.82
tip                1.75
sex                Male
smoker               No
day                 Sat
time             Dinner
size                  2
ratio         0.0982043
Name: 242, dtype: object)
(243, total_bill       18.78
tip                  3
sex             Female
smoker              No
day               Thur
time            Dinner
size                 2
ratio         0.159744
Name: 243, dtype: object)

In [20]:
for i in tips.itertuples():
    print(i)

Pandas(Index=0, total_bill=16.99, tip=1.01, sex='Female', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.05944673337257211)
Pandas(Index=1, total_bill=10.34, tip=1.66, sex='Male', smoker='No', day='Sun', time='Dinner', size=3, ratio=0.16054158607350097)
Pandas(Index=2, total_bill=21.01, tip=3.5, sex='Male', smoker='No', day='Sun', time='Dinner', size=3, ratio=0.16658733936220846)
Pandas(Index=3, total_bill=23.68, tip=3.31, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.1397804054054054)
Pandas(Index=4, total_bill=24.59, tip=3.61, sex='Female', smoker='No', day='Sun', time='Dinner', size=4, ratio=0.14680764538430255)
Pandas(Index=5, total_bill=25.29, tip=4.71, sex='Male', smoker='No', day='Sun', time='Dinner', size=4, ratio=0.18623962040332148)
Pandas(Index=6, total_bill=8.77, tip=2.0, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.22805017103762829)
Pandas(Index=7, total_bill=26.88, tip=3.12, sex='Male', smoker='No', day='Sun', time='Dinner', size=4, ratio=0.11607142857142858)
Pandas(Index=8, total_bill=15.04, tip=1.96, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.13031914893617022)
Pandas(Index=9, total_bill=14.78, tip=3.23, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.2185385656292287)
Pandas(Index=10, total_bill=10.27, tip=1.71, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.1665043816942551)
Pandas(Index=11, total_bill=35.26, tip=5.0, sex='Female', smoker='No', day='Sun', time='Dinner', size=4, ratio=0.14180374361883155)
Pandas(Index=12, total_bill=15.42, tip=1.57, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.10181582360570687)
Pandas(Index=13, total_bill=18.43, tip=3.0, sex='Male', smoker='No', day='Sun', time='Dinner', size=4, ratio=0.16277807921866522)
Pandas(Index=14, total_bill=14.83, tip=3.02, sex='Female', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.20364126770060686)
Pandas(Index=15, total_bill=21.58, tip=3.92, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.18164967562557924)
Pandas(Index=16, total_bill=10.33, tip=1.67, sex='Female', smoker='No', day='Sun', time='Dinner', size=3, ratio=0.1616650532429816)
Pandas(Index=17, total_bill=16.29, tip=3.71, sex='Male', smoker='No', day='Sun', time='Dinner', size=3, ratio=0.22774708410067526)
Pandas(Index=18, total_bill=16.97, tip=3.5, sex='Female', smoker='No', day='Sun', time='Dinner', size=3, ratio=0.20624631703005306)
Pandas(Index=19, total_bill=20.65, tip=3.35, sex='Male', smoker='No', day='Sat', time='Dinner', size=3, ratio=0.16222760290556903)
Pandas(Index=20, total_bill=17.92, tip=4.08, sex='Male', smoker='No', day='Sat', time='Dinner', size=2, ratio=0.22767857142857142)
Pandas(Index=21, total_bill=20.29, tip=2.75, sex='Female', smoker='No', day='Sat', time='Dinner', size=2, ratio=0.13553474618038444)
Pandas(Index=22, total_bill=15.77, tip=2.23, sex='Female', smoker='No', day='Sat', time='Dinner', size=2, ratio=0.14140773620798985)
Pandas(Index=23, total_bill=39.42, tip=7.58, sex='Male', smoker='No', day='Sat', time='Dinner', size=4, ratio=0.19228817858954844)
Pandas(Index=24, total_bill=19.82, tip=3.18, sex='Male', smoker='No', day='Sat', time='Dinner', size=2, ratio=0.16044399596367306)
Pandas(Index=25, total_bill=17.81, tip=2.34, sex='Male', smoker='No', day='Sat', time='Dinner', size=4, ratio=0.13138686131386862)
Pandas(Index=26, total_bill=13.37, tip=2.0, sex='Male', smoker='No', day='Sat', time='Dinner', size=2, ratio=0.14958863126402394)
Pandas(Index=27, total_bill=12.69, tip=2.0, sex='Male', smoker='No', day='Sat', time='Dinner', size=2, ratio=0.15760441292356187)
Pandas(Index=28, total_bill=21.7, tip=4.3, sex='Male', smoker='No', day='Sat', time='Dinner', size=2, ratio=0.19815668202764977)
Pandas(Index=29, total_bill=19.65, tip=3.0, sex='Female', smoker='No', day='Sat', time='Dinner', size=2, ratio=0.15267175572519084)
Pandas(Index=30, total_bill=9.55, tip=1.45, sex='Male', smoker='No', day='Sat', time='Dinner', size=2, ratio=0.1518324607329843)
Pandas(Index=31, total_bill=18.35, tip=2.5, sex='Male', smoker='No', day='Sat', time='Dinner', size=4, ratio=0.13623978201634876)
Pandas(Index=32, total_bill=15.06, tip=3.0, sex='Female', smoker='No', day='Sat', time='Dinner', size=2, ratio=0.199203187250996)
Pandas(Index=33, total_bill=20.69, tip=2.45, sex='Female', smoker='No', day='Sat', time='Dinner', size=4, ratio=0.11841469308844853)
Pandas(Index=34, total_bill=17.78, tip=3.27, sex='Male', smoker='No', day='Sat', time='Dinner', size=2, ratio=0.1839145106861642)
Pandas(Index=35, total_bill=24.06, tip=3.6, sex='Male', smoker='No', day='Sat', time='Dinner', size=3, ratio=0.14962593516209477)
Pandas(Index=36, total_bill=16.31, tip=2.0, sex='Male', smoker='No', day='Sat', time='Dinner', size=3, ratio=0.12262415695892091)
Pandas(Index=37, total_bill=16.93, tip=3.07, sex='Female', smoker='No', day='Sat', time='Dinner', size=3, ratio=0.1813349084465446)
Pandas(Index=38, total_bill=18.69, tip=2.31, sex='Male', smoker='No', day='Sat', time='Dinner', size=3, ratio=0.12359550561797752)
Pandas(Index=39, total_bill=31.27, tip=5.0, sex='Male', smoker='No', day='Sat', time='Dinner', size=3, ratio=0.1598976654940838)
Pandas(Index=40, total_bill=16.04, tip=2.24, sex='Male', smoker='No', day='Sat', time='Dinner', size=3, ratio=0.13965087281795513)
Pandas(Index=41, total_bill=17.46, tip=2.54, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.14547537227949597)
Pandas(Index=42, total_bill=13.94, tip=3.06, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.21951219512195122)
Pandas(Index=43, total_bill=9.68, tip=1.32, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.13636363636363638)
Pandas(Index=44, total_bill=30.4, tip=5.6, sex='Male', smoker='No', day='Sun', time='Dinner', size=4, ratio=0.18421052631578946)
Pandas(Index=45, total_bill=18.29, tip=3.0, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.16402405686167304)
Pandas(Index=46, total_bill=22.23, tip=5.0, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.22492127755285649)
Pandas(Index=47, total_bill=32.4, tip=6.0, sex='Male', smoker='No', day='Sun', time='Dinner', size=4, ratio=0.1851851851851852)
Pandas(Index=48, total_bill=28.55, tip=2.05, sex='Male', smoker='No', day='Sun', time='Dinner', size=3, ratio=0.07180385288966724)
Pandas(Index=49, total_bill=18.04, tip=3.0, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.16629711751662973)
Pandas(Index=50, total_bill=12.54, tip=2.5, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.19936204146730463)
Pandas(Index=51, total_bill=10.29, tip=2.6, sex='Female', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.2526724975704568)
Pandas(Index=52, total_bill=34.81, tip=5.2, sex='Female', smoker='No', day='Sun', time='Dinner', size=4, ratio=0.14938236139040506)
Pandas(Index=53, total_bill=9.94, tip=1.56, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.15694164989939638)
Pandas(Index=54, total_bill=25.56, tip=4.34, sex='Male', smoker='No', day='Sun', time='Dinner', size=4, ratio=0.1697965571205008)
Pandas(Index=55, total_bill=19.49, tip=3.51, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.18009235505387378)
Pandas(Index=56, total_bill=38.01, tip=3.0, sex='Male', smoker='Yes', day='Sat', time='Dinner', size=4, ratio=0.07892659826361484)
Pandas(Index=57, total_bill=26.41, tip=1.5, sex='Female', smoker='No', day='Sat', time='Dinner', size=2, ratio=0.05679666792881484)
Pandas(Index=58, total_bill=11.24, tip=1.76, sex='Male', smoker='Yes', day='Sat', time='Dinner', size=2, ratio=0.15658362989323843)
Pandas(Index=59, total_bill=48.27, tip=6.73, sex='Male', smoker='No', day='Sat', time='Dinner', size=4, ratio=0.13942407292314066)
Pandas(Index=60, total_bill=20.29, tip=3.21, sex='Male', smoker='Yes', day='Sat', time='Dinner', size=2, ratio=0.1582060128141942)
Pandas(Index=61, total_bill=13.81, tip=2.0, sex='Male', smoker='Yes', day='Sat', time='Dinner', size=2, ratio=0.1448225923244026)
Pandas(Index=62, total_bill=11.02, tip=1.98, sex='Male', smoker='Yes', day='Sat', time='Dinner', size=2, ratio=0.17967332123411978)
Pandas(Index=63, total_bill=18.29, tip=3.76, sex='Male', smoker='Yes', day='Sat', time='Dinner', size=4, ratio=0.20557681793329688)
Pandas(Index=64, total_bill=17.59, tip=2.64, sex='Male', smoker='No', day='Sat', time='Dinner', size=3, ratio=0.15008527572484368)
Pandas(Index=65, total_bill=20.08, tip=3.15, sex='Male', smoker='No', day='Sat', time='Dinner', size=3, ratio=0.15687250996015936)
Pandas(Index=66, total_bill=16.45, tip=2.47, sex='Female', smoker='No', day='Sat', time='Dinner', size=2, ratio=0.1501519756838906)
Pandas(Index=67, total_bill=3.07, tip=1.0, sex='Female', smoker='Yes', day='Sat', time='Dinner', size=1, ratio=0.32573289902280134)
Pandas(Index=68, total_bill=20.23, tip=2.01, sex='Male', smoker='No', day='Sat', time='Dinner', size=2, ratio=0.09935739001482945)
Pandas(Index=69, total_bill=15.01, tip=2.09, sex='Male', smoker='Yes', day='Sat', time='Dinner', size=2, ratio=0.13924050632911392)
Pandas(Index=70, total_bill=12.02, tip=1.97, sex='Male', smoker='No', day='Sat', time='Dinner', size=2, ratio=0.1638935108153078)
Pandas(Index=71, total_bill=17.07, tip=3.0, sex='Female', smoker='No', day='Sat', time='Dinner', size=3, ratio=0.1757469244288225)
Pandas(Index=72, total_bill=26.86, tip=3.14, sex='Female', smoker='Yes', day='Sat', time='Dinner', size=2, ratio=0.11690245718540582)
Pandas(Index=73, total_bill=25.28, tip=5.0, sex='Female', smoker='Yes', day='Sat', time='Dinner', size=2, ratio=0.19778481012658228)
Pandas(Index=74, total_bill=14.73, tip=2.2, sex='Female', smoker='No', day='Sat', time='Dinner', size=2, ratio=0.14935505770536323)
Pandas(Index=75, total_bill=10.51, tip=1.25, sex='Male', smoker='No', day='Sat', time='Dinner', size=2, ratio=0.11893434823977164)
Pandas(Index=76, total_bill=17.92, tip=3.08, sex='Male', smoker='Yes', day='Sat', time='Dinner', size=2, ratio=0.171875)
Pandas(Index=77, total_bill=27.2, tip=4.0, sex='Male', smoker='No', day='Thur', time='Lunch', size=4, ratio=0.14705882352941177)
Pandas(Index=78, total_bill=22.76, tip=3.0, sex='Male', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.13181019332161686)
Pandas(Index=79, total_bill=17.29, tip=2.71, sex='Male', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.156737998843262)
Pandas(Index=80, total_bill=19.44, tip=3.0, sex='Male', smoker='Yes', day='Thur', time='Lunch', size=2, ratio=0.15432098765432098)
Pandas(Index=81, total_bill=16.66, tip=3.4, sex='Male', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.20408163265306123)
Pandas(Index=82, total_bill=10.07, tip=1.83, sex='Female', smoker='No', day='Thur', time='Lunch', size=1, ratio=0.1817279046673287)
Pandas(Index=83, total_bill=32.68, tip=5.0, sex='Male', smoker='Yes', day='Thur', time='Lunch', size=2, ratio=0.15299877600979192)
Pandas(Index=84, total_bill=15.98, tip=2.03, sex='Male', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.12703379224030037)
Pandas(Index=85, total_bill=34.83, tip=5.17, sex='Female', smoker='No', day='Thur', time='Lunch', size=4, ratio=0.14843525696238874)
Pandas(Index=86, total_bill=13.03, tip=2.0, sex='Male', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.15349194167306218)
Pandas(Index=87, total_bill=18.28, tip=4.0, sex='Male', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.2188183807439825)
Pandas(Index=88, total_bill=24.71, tip=5.85, sex='Male', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.23674625657628487)
Pandas(Index=89, total_bill=21.16, tip=3.0, sex='Male', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.14177693761814744)
Pandas(Index=90, total_bill=28.97, tip=3.0, sex='Male', smoker='Yes', day='Fri', time='Dinner', size=2, ratio=0.10355540214014498)
Pandas(Index=91, total_bill=22.49, tip=3.5, sex='Male', smoker='No', day='Fri', time='Dinner', size=2, ratio=0.15562472209871056)
Pandas(Index=92, total_bill=5.75, tip=1.0, sex='Female', smoker='Yes', day='Fri', time='Dinner', size=2, ratio=0.17391304347826086)
Pandas(Index=93, total_bill=16.32, tip=4.3, sex='Female', smoker='Yes', day='Fri', time='Dinner', size=2, ratio=0.26348039215686275)
Pandas(Index=94, total_bill=22.75, tip=3.25, sex='Female', smoker='No', day='Fri', time='Dinner', size=2, ratio=0.14285714285714285)
Pandas(Index=95, total_bill=40.17, tip=4.73, sex='Male', smoker='Yes', day='Fri', time='Dinner', size=4, ratio=0.1177495643515061)
Pandas(Index=96, total_bill=27.28, tip=4.0, sex='Male', smoker='Yes', day='Fri', time='Dinner', size=2, ratio=0.14662756598240467)
Pandas(Index=97, total_bill=12.03, tip=1.5, sex='Male', smoker='Yes', day='Fri', time='Dinner', size=2, ratio=0.12468827930174564)
Pandas(Index=98, total_bill=21.01, tip=3.0, sex='Male', smoker='Yes', day='Fri', time='Dinner', size=2, ratio=0.1427891480247501)
Pandas(Index=99, total_bill=12.46, tip=1.5, sex='Male', smoker='No', day='Fri', time='Dinner', size=2, ratio=0.1203852327447833)
Pandas(Index=100, total_bill=11.35, tip=2.5, sex='Female', smoker='Yes', day='Fri', time='Dinner', size=2, ratio=0.22026431718061676)
Pandas(Index=101, total_bill=15.38, tip=3.0, sex='Female', smoker='Yes', day='Fri', time='Dinner', size=2, ratio=0.19505851755526657)
Pandas(Index=102, total_bill=44.3, tip=2.5, sex='Female', smoker='Yes', day='Sat', time='Dinner', size=3, ratio=0.05643340857787811)
Pandas(Index=103, total_bill=22.42, tip=3.48, sex='Female', smoker='Yes', day='Sat', time='Dinner', size=2, ratio=0.15521855486173058)
Pandas(Index=104, total_bill=20.92, tip=4.08, sex='Female', smoker='No', day='Sat', time='Dinner', size=2, ratio=0.1950286806883365)
Pandas(Index=105, total_bill=15.36, tip=1.64, sex='Male', smoker='Yes', day='Sat', time='Dinner', size=2, ratio=0.10677083333333333)
Pandas(Index=106, total_bill=20.49, tip=4.06, sex='Male', smoker='Yes', day='Sat', time='Dinner', size=2, ratio=0.19814543679843827)
Pandas(Index=107, total_bill=25.21, tip=4.29, sex='Male', smoker='Yes', day='Sat', time='Dinner', size=2, ratio=0.1701705672352241)
Pandas(Index=108, total_bill=18.24, tip=3.76, sex='Male', smoker='No', day='Sat', time='Dinner', size=2, ratio=0.20614035087719298)
Pandas(Index=109, total_bill=14.31, tip=4.0, sex='Female', smoker='Yes', day='Sat', time='Dinner', size=2, ratio=0.2795248078266946)
Pandas(Index=110, total_bill=14.0, tip=3.0, sex='Male', smoker='No', day='Sat', time='Dinner', size=2, ratio=0.21428571428571427)
Pandas(Index=111, total_bill=7.25, tip=1.0, sex='Female', smoker='No', day='Sat', time='Dinner', size=1, ratio=0.13793103448275862)
Pandas(Index=112, total_bill=38.07, tip=4.0, sex='Male', smoker='No', day='Sun', time='Dinner', size=3, ratio=0.10506960861570791)
Pandas(Index=113, total_bill=23.95, tip=2.55, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.10647181628392484)
Pandas(Index=114, total_bill=25.71, tip=4.0, sex='Female', smoker='No', day='Sun', time='Dinner', size=3, ratio=0.15558148580318942)
Pandas(Index=115, total_bill=17.31, tip=3.5, sex='Female', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.20219526285384173)
Pandas(Index=116, total_bill=29.93, tip=5.07, sex='Male', smoker='No', day='Sun', time='Dinner', size=4, ratio=0.1693952555963916)
Pandas(Index=117, total_bill=10.65, tip=1.5, sex='Female', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.14084507042253522)
Pandas(Index=118, total_bill=12.43, tip=1.8, sex='Female', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.14481094127111827)
Pandas(Index=119, total_bill=24.08, tip=2.92, sex='Female', smoker='No', day='Thur', time='Lunch', size=4, ratio=0.1212624584717608)
Pandas(Index=120, total_bill=11.69, tip=2.31, sex='Male', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.19760479041916168)
Pandas(Index=121, total_bill=13.42, tip=1.68, sex='Female', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.12518628912071533)
Pandas(Index=122, total_bill=14.26, tip=2.5, sex='Male', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.1753155680224404)
Pandas(Index=123, total_bill=15.95, tip=2.0, sex='Male', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.12539184952978058)
Pandas(Index=124, total_bill=12.48, tip=2.52, sex='Female', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.20192307692307693)
Pandas(Index=125, total_bill=29.8, tip=4.2, sex='Female', smoker='No', day='Thur', time='Lunch', size=6, ratio=0.14093959731543623)
Pandas(Index=126, total_bill=8.52, tip=1.48, sex='Male', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.17370892018779344)
Pandas(Index=127, total_bill=14.52, tip=2.0, sex='Female', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.13774104683195593)
Pandas(Index=128, total_bill=11.38, tip=2.0, sex='Female', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.17574692442882248)
Pandas(Index=129, total_bill=22.82, tip=2.18, sex='Male', smoker='No', day='Thur', time='Lunch', size=3, ratio=0.09553023663453111)
Pandas(Index=130, total_bill=19.08, tip=1.5, sex='Male', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.07861635220125787)
Pandas(Index=131, total_bill=20.27, tip=2.83, sex='Female', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.13961519486926494)
Pandas(Index=132, total_bill=11.17, tip=1.5, sex='Female', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.13428827215756492)
Pandas(Index=133, total_bill=12.26, tip=2.0, sex='Female', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.1631321370309951)
Pandas(Index=134, total_bill=18.26, tip=3.25, sex='Female', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.17798466593647316)
Pandas(Index=135, total_bill=8.51, tip=1.25, sex='Female', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.14688601645123384)
Pandas(Index=136, total_bill=10.33, tip=2.0, sex='Female', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.1936108422071636)
Pandas(Index=137, total_bill=14.15, tip=2.0, sex='Female', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.1413427561837456)
Pandas(Index=138, total_bill=16.0, tip=2.0, sex='Male', smoker='Yes', day='Thur', time='Lunch', size=2, ratio=0.125)
Pandas(Index=139, total_bill=13.16, tip=2.75, sex='Female', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.20896656534954408)
Pandas(Index=140, total_bill=17.47, tip=3.5, sex='Female', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.20034344590726963)
Pandas(Index=141, total_bill=34.3, tip=6.7, sex='Male', smoker='No', day='Thur', time='Lunch', size=6, ratio=0.19533527696793004)
Pandas(Index=142, total_bill=41.19, tip=5.0, sex='Male', smoker='No', day='Thur', time='Lunch', size=5, ratio=0.12138868657441128)
Pandas(Index=143, total_bill=27.05, tip=5.0, sex='Female', smoker='No', day='Thur', time='Lunch', size=6, ratio=0.18484288354898337)
Pandas(Index=144, total_bill=16.43, tip=2.3, sex='Female', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.1399878271454656)
Pandas(Index=145, total_bill=8.35, tip=1.5, sex='Female', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.17964071856287425)
Pandas(Index=146, total_bill=18.64, tip=1.36, sex='Female', smoker='No', day='Thur', time='Lunch', size=3, ratio=0.07296137339055794)
Pandas(Index=147, total_bill=11.87, tip=1.63, sex='Female', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.13732097725358045)
Pandas(Index=148, total_bill=9.78, tip=1.73, sex='Male', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.1768916155419223)
Pandas(Index=149, total_bill=7.51, tip=2.0, sex='Male', smoker='No', day='Thur', time='Lunch', size=2, ratio=0.2663115845539281)
Pandas(Index=150, total_bill=14.07, tip=2.5, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.17768301350390903)
Pandas(Index=151, total_bill=13.13, tip=2.0, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, ratio=0.15232292460015232)